### ISSUE TITLE
null pointer exception (graphsense-transformation)

### ISSUE THREAD

**Issue by GNSNa** [graphsense/graphsense-setup#9]
Dears,

We've faced with error during execution graphsense-transformation (bitcoin) launched in a docker container.
Could you help to identify the reason of the error and ways to fix it?

Thank you beforehad.

Please find error text below:
--===================================
Computing exchange rates
[2021-12-13 10:06:30] Writing table exchange_rates
Time: 00:00:13
Extracting transaction inputs
Extracting transaction outputs
Computing address IDs
[2021-12-13 10:16:00] Writing table address_ids_by_address_prefix
Time: 00:14:55
Computing address transactions
[2021-12-13 10:30:56] Writing table address_transactions
Time: 00:33:11
Computing address statistics
Computing address tags
[2021-12-13 11:04:08] Writing table address_tags
Time: 00:03:55
[2021-12-13 11:08:03] Writing table address_tag_by_label
Time: 00:00:03
Computing plain address relations
Computing address relations
[2021-12-13 11:21:38] Writing table address_incoming_relations
21/12/13 11:22:23 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 268.0 (TID 26006, 10.4.19.12, executor 0): java.lang.NullPointerException: Null value appeared in non-nullable field:
- array element class: "scala.Float"
- field (class: "scala.collection.Seq", name: "fiatValues")
- field (class: "info.graphsense.Currency", name: "estimatedValue")
- root class: "info.graphsense.AddressRelation"
If the schema is inferred from a Scala tuple/case class, or a Java bean, please try to use scala.Option[_] or other nullable types (e.g. java.lang.Integer instead of int/scala.Int).
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.MapObjects_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.NewInstance_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at com.datastax.spark.connector.util.CountingIterator.next(CountingIterator.scala:16)
        at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:106)
        at com.datastax.spark.connector.writer.GroupingBatchBuilder.next(GroupingBatchBuilder.scala:31)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at com.datastax.spark.connector.writer.GroupingBatchBuilder.foreach(GroupingBatchBuilder.scala:31)
        at com.datastax.spark.connector.writer.TableWriter.$anonfun$writeInternal$1(TableWriter.scala:233)
        at com.datastax.spark.connector.writer.TableWriter.$anonfun$writeInternal$1$adapted(TableWriter.scala:210)
        at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:112)
        at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:145)
        at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
        at com.datastax.spark.connector.writer.TableWriter.writeInternal(TableWriter.scala:210)
        at com.datastax.spark.connector.writer.TableWriter.insert(TableWriter.scala:197)
        at com.datastax.spark.connector.writer.TableWriter.write(TableWriter.scala:183)
        at com.datastax.spark.connector.RDDFunctions.$anonfun$saveToCassandra$1(RDDFunctions.scala:36)
        at com.datastax.spark.connector.RDDFunctions.$anonfun$saveToCassandra$1$adapted(RDDFunctions.scala:36)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by defconst** [comment]
There is a problem in your data, maybe your raw keyspace is incomplete (or something unexpected in tags or exchange rates).
If the data set is incomplete, some joins may produce NULL values in some tables.
